{% set name = "gsshapyorm" %}
{% set version = "0.4.3" %}
{% set sha256 = "ca6c59e4915dfd5c06e2293ed33f749837dc9aee88ff551853a90708453d7e62" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - appdirs
  run:
    - python >={{ python_min }}
    - appdirs
    - geopandas
    - mapkit >=1.2.6
    - numpy
    - pandas
    - psycopg2
    - pyyaml
    - sqlalchemy <2
    - timezonefinder

test:
  requires:
    - python {{ python_min }}
  imports:
    - gsshapyorm
    - gsshapyorm.orm
    - gsshapyorm.orm.file_io
    - gsshapyorm.orm.prj
    - gsshapyorm.lib
    - gsshapyorm.lib.db_tools
    - gsshapyorm.util

about:
  home: https://github.com/Aquaveo/gsshapyorm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'SQLAlchemy Object Relational Model for GSSHA model files.'
  description: |
    GsshaPy is an object relational model (ORM) for the
    Gridded Surface Subsurface Hydrologic Analysis (GSSHA) model.
    The purpose of gsshapyorm is to expose GSSHA files to a web
    development environment by reading them into an SQL database.
    The files can also be written back to file for model execution.
  doc_url: http://gsshapyorm.readthedocs.io
  dev_url: https://github.com/Aquaveo/gsshapyorm

extra:
  recipe-maintainers:
    - swainn
